faiss_db:
  collection_yaml: "document_portal"

embedding_model:
  embedding_model:
  provider: huggingface
  model_name: sentence-transformers/all-MiniLM-L6-v2


retriever:
  top_k: 10

llm:
  provider: "Groq"
  model_name: "deepseek-r1-distill-llama-70b"
  temperature: 0
  max_output_tokens: 2048

google:
  provider: "Google"
  model_name: "gemini-2.0-flash"
  temperature: 0
  max_output_tokens: 2048
